spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campeonatosfifa
    username: postgres
    password: YEca4941*%
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect